"""
Script 05: Run Temperature=0.0 Robustness Pass (N=30 per cell)
==============================================================
Runs the ROBUSTNESS_T0_DESIGN manifest (10 models × 5 bias types × 2 variants
× 30 runs at T=0.0 = 3,000 runs ≈ $450, ~10 hours).

PURPOSE:
  Verify that BSI results from the realistic design (T=0.7) are not stochastic
  artifacts of temperature sampling.  At T=0.0, model outputs are deterministic
  conditional on prompt content, so any remaining BSI reflects systematic bias
  in the decision logic rather than random token sampling variance.

  If realistic-design BSI collapses to ≈0 at T=0.0, the result is a stochastic
  artifact and the paper must acknowledge this.  If BSI persists at T=0.0, the
  finding is temperature-robust and the claim is strengthened.

GATE 1 ENFORCEMENT (Section O.3):
  Before executing, this script reads ``ceiling_effect.json`` from a completed
  pilot_full experiment directory and verifies Gate 1 has been cleared:
    1. Error rate < 5%  (infrastructure healthy)
    2. ≥2/10 models show mean_BSI > 0.05 on ≥1 bias type  (BSI variation exists)
  If Gate 1 has not passed, the script exits with status 1 to prevent spending
  ~$450 on an inconclusive run.  Use ``--skip-gate1`` to bypass this check.

Prerequisites:
  - OPENROUTER_API_KEY must be set (or pass --mock for local validation)
  - pip install -e ".[dev]" completed
  - A completed pilot_full run with ceiling_effect.json, generated by:
      python research/scripts/03_analyze_ceiling_effect.py \\
             --experiment-dir results/experiments/{pilot_full_dir}

Flags:
  --pilot-dir DIR     Path to completed pilot_full experiment directory
                      (must contain ceiling_effect.json).  Required unless
                      --skip-gate1 or --mock is passed.
  --skip-gate1        Bypass Gate 1 check.  Use only with explicit justification.
  --dry-run           Print plan + cost estimate without invoking any models.
  --resume            Skip already-completed runs (restart after crash).
  --mock              Substitute mock-agent-v1 for all models (free; validates
                      the full pipeline without API credentials or Gate 1).
  --output-dir DIR    Override experiment output directory
                      (default: results/experiments).
  --no-pin-versions   Skip OpenRouter model-version pinning (offline / CI use).

Run: python research/scripts/05_run_robustness_t0.py \\
         --pilot-dir results/experiments/{pilot_full_id}
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from research.experiments.grid import ROBUSTNESS_T0_DESIGN  # noqa: E402
from research.experiments.manifest import create_manifest, freeze_manifest  # noqa: E402
from research.experiments.run_experiment import (  # noqa: E402
    estimate_cost,
    generate_run_plan,
    run_experiment,
)


# ── Gate 1 loader (mirrors 02_run_full_experiment.py) ─────────────────────────


def load_gate1_result(pilot_dir: Path) -> dict:
    """Load the Gate 1 decision from ``ceiling_effect.json`` in *pilot_dir*.

    Returns the ``gate1`` sub-dict from the ceiling effect analysis.  Raises
    ``FileNotFoundError`` if the file is absent and ``KeyError`` if the ``gate1``
    key is missing (e.g., an older analysis was run before gate1 was added).
    """
    ceiling_path = pilot_dir / "ceiling_effect.json"
    if not ceiling_path.exists():
        raise FileNotFoundError(
            f"ceiling_effect.json not found in {pilot_dir}.\n"
            "Generate it first:\n"
            f"  python research/scripts/03_analyze_ceiling_effect.py "
            f"--experiment-dir {pilot_dir}"
        )
    data = json.loads(ceiling_path.read_text(encoding="utf-8"))
    if "gate1" not in data:
        raise KeyError(
            f"'gate1' key not found in {ceiling_path}. "
            "Re-run 03_analyze_ceiling_effect.py with the latest code."
        )
    return data["gate1"]


def check_gate1(pilot_dir: Path) -> None:
    """Exit with status 1 if Gate 1 has not been cleared.

    Reads ``ceiling_effect.json`` from *pilot_dir* and prints a summary.
    If ``gate1.proceed`` is False, prints the failure reason and raises
    ``SystemExit(1)``.
    """
    gate1 = load_gate1_result(pilot_dir)
    print("Gate 1 status:")
    print(f"  Criterion 1 (error rate)    : {gate1['criterion1_detail']}")
    print(f"  Criterion 2 (BSI variation) : {gate1['criterion2_detail']}")
    print(f"  Recommendation : {gate1['recommendation']}")
    print()

    if not gate1["proceed"]:
        print("ERROR: Gate 1 has NOT been cleared.  Aborting T=0.0 robustness pass.")
        print("Fix the issues above and re-run the pilot_full experiment, then")
        print("re-analyze with 03_analyze_ceiling_effect.py before retrying.")
        print("(Pass --skip-gate1 to bypass this check at your own risk.)")
        raise SystemExit(1)

    print("[Gate 1 PASSED]  Proceeding to T=0.0 robustness pass (N=30 per cell).")
    print()


# ── Main ──────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="python research/scripts/05_run_robustness_t0.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--pilot-dir",
        type=Path,
        metavar="DIR",
        help=(
            "Path to the completed pilot_full experiment directory "
            "(must contain ceiling_effect.json).  Required unless --skip-gate1 "
            "or --mock is passed."
        ),
    )
    parser.add_argument(
        "--skip-gate1",
        action="store_true",
        help="Bypass Gate 1 check.  Use only with explicit justification.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print plan + cost estimate without invoking any models.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip run_ids already present in runs.jsonl (restart after crash).",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help=(
            "Replace all 10 real models with mock-agent-v1. "
            "Free and fast; implies --skip-gate1 (no pilot_dir required)."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/experiments"),
        metavar="DIR",
        help="Parent directory for experiment outputs (default: results/experiments).",
    )
    parser.add_argument(
        "--no-pin-versions",
        action="store_true",
        help="Skip OpenRouter model-version pinning (useful for offline / CI use).",
    )
    args = parser.parse_args(argv)

    # --mock implies --skip-gate1: pipeline validation doesn't need a pilot.
    skip_gate1 = args.skip_gate1 or args.mock

    # Gate 1 enforcement.
    if not skip_gate1:
        if args.pilot_dir is None:
            parser.error(
                "--pilot-dir is required unless --skip-gate1 or --mock is passed.\n"
                "Point it to the completed pilot_full experiment directory that "
                "contains ceiling_effect.json."
            )
        check_gate1(args.pilot_dir)
    elif args.skip_gate1 and not args.mock:
        print("[--skip-gate1] Gate 1 check bypassed — proceeding without verification.")
        print()

    # Build design (swap in mock agent if requested).
    design = dict(ROBUSTNESS_T0_DESIGN)
    if args.mock:
        design = {
            **design,
            "models": ["mock-agent-v1"],
            "cost_per_run_usd": 0.00,
        }
        print("[--mock] Substituting mock-agent-v1 for all real models.")

    output_dir: Path = args.output_dir

    # 1. Build and freeze manifest.
    print(
        f"Building robustness_t0 manifest "
        f"(T=0.0, N={design['n_runs_per_cell']} per cell)…"
    )
    manifest = create_manifest(
        design,
        pin_model_versions=not args.no_pin_versions,
    )
    manifest_path = freeze_manifest(manifest, output_dir)
    exp_dir = manifest_path.parent
    print(f"Manifest written : {manifest_path}")

    # 2. Generate run plan and write run_plan.csv.
    manifest_dict = json.loads(manifest_path.read_text(encoding="utf-8"))
    runs = generate_run_plan(manifest_dict)
    run_plan_path = exp_dir / "run_plan.csv"
    with open(run_plan_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(runs[0].keys()))
        writer.writeheader()
        writer.writerows(runs)
    print(f"Run plan written : {run_plan_path}  ({len(runs):,} runs)")

    # 3. Write cost estimate.
    cost = estimate_cost(len(runs), design["cost_per_run_usd"])
    cost_path = exp_dir / "cost_estimate.txt"
    cost_path.write_text(json.dumps(cost, indent=2), encoding="utf-8")
    print(
        f"Cost estimate    : ${cost['estimated_total_usd']:.2f} for {cost['n_runs']:,} runs"
    )
    print()

    # 4. Execute or display dry-run summary.
    run_experiment(
        manifest_path=manifest_path,
        output_dir=exp_dir,
        dry_run=args.dry_run,
        resume=args.resume,
    )

    if not args.dry_run:
        print()
        print("Next step — compare T=0.7 realistic vs T=0.0 robustness BSI:")
        print(
            f"  python research/scripts/03_run_regressions.py "
            f"--experiment-dir {exp_dir}"
        )
        print(
            "  Compare bsi_mean across designs to check for temperature-driven "
            "stochastic artifacts."
        )


if __name__ == "__main__":
    main()
