"""
Script 08: Run Flagship LLM Experiments (N=100 per cell; 8 bias types)
=======================================================================
Runs the FLAGSHIP_DESIGN manifest (10 models × 8 bias types × 17 scenario
slots × 2 temperatures × 2 prompt versions × 100 runs = 68,000 runs ≈
$13,600, ~50–60 hours).

FLAGSHIP EXPANSION (UPGRADE-8/9/10):
  The flagship design extends the realistic design's 5 standard bias types
  with three new types:
    - UPGRADE-8  p2-06-default       (status-quo / default bias)
    - UPGRADE-9  p2-07-loss-aversion (loss-aversion switching cost)
    - UPGRADE-10 p2-08-warp          (WARP transitivity triplet: AB, BC, AC)
  Two temperatures (0.7 and 0.0) and two prompt versions (standard and cot)
  are run in the same experiment to enable within-experiment robustness checks.
  WARP uses three scenario slots (warp_ab, warp_bc, warp_ac); all other bias
  types use two (baseline + treatment).  Total scenario slots = 17.

GATE 3 ENFORCEMENT (Section O.3):
  Before executing, this script verifies Gate 3 has been cleared from a
  completed full realistic N=50 experiment:
    1. ≥3/10 models show statistically detectable bias on ≥2/5 bias types
       (95% CI lower bound > 0 on treatment cells)
  If Gate 3 has not passed, the script exits with status 1.  An alternative
  "robust rationality" framing is suggested if all models show BSI ≈ 0.
  Use ``--skip-gate3`` to bypass this check.

  To generate the gate3.json file from a completed realistic experiment:
    python research/scripts/08_run_flagship.py --full-dir <realistic_dir> --analyze-gate3

Prerequisites:
  - OPENROUTER_API_KEY must be set (or pass --mock for local validation)
  - pip install -e ".[dev]" completed
  - A completed realistic N=50 experiment with cells.json, generated by:
      python research/scripts/02_run_full_experiment.py
      python research/scripts/02_aggregate_results.py --experiment-dir <dir>

Flags:
  --full-dir DIR      Path to the completed realistic N=50 experiment directory
                      (must contain cells.json or gate3.json).  Required unless
                      --skip-gate3 or --mock is passed.
  --skip-gate3        Bypass Gate 3 check.  Use only with explicit justification.
  --analyze-gate3     Compute gate3.json from cells.json in --full-dir, then exit.
  --dry-run           Print plan + cost estimate without invoking any models.
  --resume            Skip already-completed runs (restart after crash).
  --mock              Substitute mock-agent-v1 for all models (free; validates
                      the full pipeline without API credentials or Gate 3).
  --output-dir DIR    Override experiment output directory
                      (default: results/experiments).
  --no-pin-versions   Skip OpenRouter model-version pinning (offline / CI use).

Run: python research/scripts/08_run_flagship.py \\
         --full-dir results/experiments/{realistic_id}
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from research.experiments.grid import FLAGSHIP_DESIGN  # noqa: E402
from research.experiments.manifest import create_manifest, freeze_manifest  # noqa: E402
from research.experiments.run_experiment import (  # noqa: E402
    estimate_cost,
    generate_run_plan,
    run_experiment,
)

# Gate 3 thresholds (O.3 criteria).
GATE3_MIN_MODELS = 3
GATE3_MIN_BIAS_TYPES = 2
GATE3_BSI_CI_FLOOR = 0.0  # treatment-cell ci_lower_95 must exceed this


# ── Gate 3 computation ────────────────────────────────────────────────────────


def compute_gate3_from_cells(cells_path: Path) -> dict:
    """Compute the Gate 3 decision from a ``cells.json`` cell-aggregate file.

    Gate 3 (O.3): ≥GATE3_MIN_MODELS models each show statistically detectable
    bias on ≥GATE3_MIN_BIAS_TYPES bias types, where "detectable" is defined as
    the treatment-cell 95% CI lower bound strictly exceeding GATE3_BSI_CI_FLOOR.

    Parameters
    ----------
    cells_path:
        Path to ``cells.json`` produced by ``02_aggregate_results.py``.

    Returns
    -------
    dict with keys:
      ``proceed`` (bool), ``n_models_with_bias`` (int),
      ``per_model`` (dict), ``criterion_detail`` (str),
      ``recommendation`` (str), ``robust_rationality_pivot`` (bool).
    """
    cells = json.loads(cells_path.read_text(encoding="utf-8"))
    if isinstance(cells, dict) and "cells" in cells:
        cells = cells["cells"]

    per_model: dict[str, list[str]] = {}
    for cell in cells:
        agent_id = cell.get("agent_id", "")
        variant = cell.get("variant", "")
        bias_cat = cell.get("bias_category", "")
        ci_lower = cell.get("ci_lower_95", 0.0)
        if variant.lower() in ("treatment", "anchor_high", "loss", "decoy", "scarcity",
                                "sunk_cost", "default", "loss_aversion",
                                "warp_ab", "warp_bc", "warp_ac"):
            if ci_lower > GATE3_BSI_CI_FLOOR:
                per_model.setdefault(agent_id, [])
                if bias_cat not in per_model[agent_id]:
                    per_model[agent_id].append(bias_cat)

    qualifying: dict[str, int] = {
        model: len(bias_types)
        for model, bias_types in per_model.items()
        if len(bias_types) >= GATE3_MIN_BIAS_TYPES
    }
    n_qualifying = len(qualifying)
    proceed = n_qualifying >= GATE3_MIN_MODELS
    robust_rationality = len(per_model) == 0

    if proceed:
        recommendation = (
            f"Gate 3 PASSED — {n_qualifying} model(s) show detectable bias on "
            f"≥{GATE3_MIN_BIAS_TYPES} bias types.  Proceed to flagship experiment."
        )
    elif robust_rationality:
        recommendation = (
            "Gate 3 FAILED — no models show detectable bias.  "
            "Pivot to 'robust rationality' framing (still publishable).  "
            "Do NOT proceed with flagship unless paper angle is revised."
        )
    else:
        recommendation = (
            f"Gate 3 FAILED — only {n_qualifying}/{GATE3_MIN_MODELS} required models "
            f"show detectable bias on ≥{GATE3_MIN_BIAS_TYPES} bias types.  "
            "Consider activating REV-4 hard-difficulty scenarios and re-running N=50."
        )

    return {
        "proceed": proceed,
        "n_models_with_bias": n_qualifying,
        "qualifying_models": qualifying,
        "per_model_bias_counts": {m: len(v) for m, v in per_model.items()},
        "criterion_detail": (
            f"{n_qualifying} model(s) qualify (need ≥{GATE3_MIN_MODELS}); "
            f"qualifying = detectable bias on ≥{GATE3_MIN_BIAS_TYPES} bias types "
            f"(ci_lower_95 > {GATE3_BSI_CI_FLOOR})"
        ),
        "recommendation": recommendation,
        "robust_rationality_pivot": robust_rationality,
        "gate3_min_models": GATE3_MIN_MODELS,
        "gate3_min_bias_types": GATE3_MIN_BIAS_TYPES,
    }


def analyze_gate3(full_dir: Path) -> dict:
    """Compute gate3.json from ``cells.json`` in *full_dir* and write it.

    If ``cells.json`` is absent, raises ``FileNotFoundError``.  If
    ``gate3.json`` already exists it is overwritten (re-analysis is safe
    because the inputs are immutable once the experiment completes).

    Returns the gate3 result dict.
    """
    cells_path = full_dir / "cells.json"
    if not cells_path.exists():
        raise FileNotFoundError(
            f"cells.json not found in {full_dir}.\n"
            "Generate it first by running:\n"
            f"  python research/scripts/02_aggregate_results.py "
            f"--experiment-dir {full_dir}"
        )
    gate3 = compute_gate3_from_cells(cells_path)
    gate3_path = full_dir / "gate3.json"
    gate3_path.write_text(
        json.dumps({"gate3": gate3}, indent=2), encoding="utf-8"
    )
    return gate3


# ── Gate 3 loader ─────────────────────────────────────────────────────────────


def load_gate3_result(full_dir: Path) -> dict:
    """Load the Gate 3 decision from *full_dir*.

    Tries ``gate3.json`` first.  If absent, attempts to compute it on the
    fly from ``cells.json``.  Raises ``FileNotFoundError`` if neither file
    is present.

    Returns the ``gate3`` sub-dict.
    """
    gate3_path = full_dir / "gate3.json"
    if gate3_path.exists():
        data = json.loads(gate3_path.read_text(encoding="utf-8"))
        if "gate3" not in data:
            raise KeyError(
                f"'gate3' key not found in {gate3_path}. "
                "Re-run with --analyze-gate3 to regenerate."
            )
        return data["gate3"]

    cells_path = full_dir / "cells.json"
    if cells_path.exists():
        return analyze_gate3(full_dir)

    raise FileNotFoundError(
        f"Neither gate3.json nor cells.json found in {full_dir}.\n"
        "Run the full realistic experiment first:\n"
        "  python research/scripts/02_run_full_experiment.py --pilot-dir <pilot_dir>\n"
        "Then aggregate results:\n"
        f"  python research/scripts/02_aggregate_results.py --experiment-dir {full_dir}"
    )


def check_gate3(full_dir: Path) -> None:
    """Exit with status 1 if Gate 3 has not been cleared.

    Reads (or computes) the Gate 3 decision from *full_dir* and prints a
    summary.  If ``gate3.proceed`` is False, prints the recommendation and
    raises ``SystemExit(1)``.
    """
    gate3 = load_gate3_result(full_dir)
    print("Gate 3 status:")
    print(f"  Criterion (detectable bias)  : {gate3['criterion_detail']}")
    print(f"  Recommendation               : {gate3['recommendation']}")
    if gate3.get("robust_rationality_pivot"):
        print()
        print(
            "  *** ROBUST RATIONALITY PIVOT: All models show BSI ≈ 0. ***"
        )
        print(
            "  Consider pivoting to a 'LLMs show robust rationality in procurement"
        )
        print(
            "  decisions' paper — this is publishable with a different angle."
        )
    print()

    if not gate3["proceed"]:
        print("ERROR: Gate 3 has NOT been cleared.  Aborting flagship experiment.")
        print(
            "Resolve the issues above (e.g., activate REV-4 hard scenarios, re-run"
        )
        print(
            "full realistic experiment) before proceeding to flagship scale."
        )
        print("(Pass --skip-gate3 to bypass this check at your own risk.)")
        raise SystemExit(1)

    print(
        f"[Gate 3 PASSED]  Proceeding to flagship experiment "
        f"(N={FLAGSHIP_DESIGN['n_runs_per_cell']} per cell, "
        f"8 bias types, 2 temperatures, 2 prompt versions)."
    )
    print()


# ── Main ──────────────────────────────────────────────────────────────────────


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(
        prog="python research/scripts/08_run_flagship.py",
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "--full-dir",
        type=Path,
        metavar="DIR",
        help=(
            "Path to the completed realistic N=50 experiment directory "
            "(must contain cells.json or gate3.json).  Required unless "
            "--skip-gate3 or --mock is passed."
        ),
    )
    parser.add_argument(
        "--skip-gate3",
        action="store_true",
        help="Bypass Gate 3 check.  Use only with explicit justification.",
    )
    parser.add_argument(
        "--analyze-gate3",
        action="store_true",
        help=(
            "Compute gate3.json from cells.json in --full-dir, print the result, "
            "and exit.  Does not run any experiments."
        ),
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print plan + cost estimate without invoking any models.",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Skip run_ids already present in runs.jsonl (restart after crash).",
    )
    parser.add_argument(
        "--mock",
        action="store_true",
        help=(
            "Replace all 10 real models with mock-agent-v1. "
            "Free and fast; implies --skip-gate3 (no full-dir required)."
        ),
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("results/experiments"),
        metavar="DIR",
        help="Parent directory for experiment outputs (default: results/experiments).",
    )
    parser.add_argument(
        "--no-pin-versions",
        action="store_true",
        help="Skip OpenRouter model-version pinning (useful for offline / CI use).",
    )
    args = parser.parse_args(argv)

    # --analyze-gate3: compute and display gate3.json, then exit.
    if args.analyze_gate3:
        if args.full_dir is None:
            parser.error("--full-dir is required when using --analyze-gate3.")
        gate3 = analyze_gate3(args.full_dir)
        print(json.dumps({"gate3": gate3}, indent=2))
        raise SystemExit(0)

    # --mock implies --skip-gate3: pipeline validation doesn't need a full run.
    skip_gate3 = args.skip_gate3 or args.mock

    # Gate 3 enforcement.
    if not skip_gate3:
        if args.full_dir is None:
            parser.error(
                "--full-dir is required unless --skip-gate3 or --mock is passed.\n"
                "Point it to the completed realistic N=50 experiment directory that "
                "contains cells.json (or gate3.json)."
            )
        check_gate3(args.full_dir)
    elif args.skip_gate3 and not args.mock:
        print("[--skip-gate3] Gate 3 check bypassed — proceeding without verification.")
        print()

    # Build design (swap in mock agent if requested).
    design = dict(FLAGSHIP_DESIGN)
    if args.mock:
        design = {
            **design,
            "models": ["mock-agent-v1"],
            "cost_per_run_usd": 0.00,
        }
        print("[--mock] Substituting mock-agent-v1 for all real models.")

    output_dir: Path = args.output_dir

    # 1. Build and freeze manifest.
    n_runs = design["n_runs_per_cell"]
    temps = design["temperatures"]
    prompts = design["prompt_versions"]
    print(
        f"Building flagship manifest "
        f"(8 bias types, N={n_runs}/cell, T∈{temps}, prompts={prompts})…"
    )
    manifest = create_manifest(
        design,
        pin_model_versions=not args.no_pin_versions,
    )
    manifest_path = freeze_manifest(manifest, output_dir)
    exp_dir = manifest_path.parent
    print(f"Manifest written : {manifest_path}")

    # 2. Generate run plan and write run_plan.csv.
    manifest_dict = json.loads(manifest_path.read_text(encoding="utf-8"))
    runs = generate_run_plan(manifest_dict)
    run_plan_path = exp_dir / "run_plan.csv"
    with open(run_plan_path, "w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(runs[0].keys()))
        writer.writeheader()
        writer.writerows(runs)
    print(f"Run plan written : {run_plan_path}  ({len(runs):,} runs)")

    # 3. Write cost estimate.
    cost = estimate_cost(len(runs), design["cost_per_run_usd"])
    cost_path = exp_dir / "cost_estimate.txt"
    cost_path.write_text(json.dumps(cost, indent=2), encoding="utf-8")
    print(
        f"Cost estimate    : ${cost['estimated_total_usd']:.2f} "
        f"for {cost['n_runs']:,} runs"
    )
    print()

    # 4. Execute or display dry-run summary.
    run_experiment(
        manifest_path=manifest_path,
        output_dir=exp_dir,
        dry_run=args.dry_run,
        resume=args.resume,
    )

    if not args.dry_run:
        print()
        print("Next steps — flagship analysis pipeline:")
        print(
            f"  python research/scripts/02_aggregate_results.py "
            f"--experiment-dir {exp_dir}"
        )
        print(
            f"  python research/scripts/03_run_regressions.py "
            f"--experiment-dir {exp_dir}"
        )
        print(
            f"  python research/scripts/04_generate_figures.py "
            f"--experiment-dir {exp_dir}"
        )
        print(
            "  Include WARP transitivity violations via "
            "evaluators.pillar2.compute_warp_transitivity()."
        )


if __name__ == "__main__":
    main()
